### PR TITLE
chore(catppuccin): Update integration and options.

### PR DESCRIPTION
**Pull request by Jint-lzxy**

### CODE REVIEW

**Review by ayamir — APPROVED** [review]

**Comment by nullchilly** [comment]
@Jint-lzxy @ayamir I put your configuration in catppuccin/nvim here: https://github.com/catppuccin/nvim#previews

What do you think? :)

**Comment by Jint-lzxy** [comment]
Good call ❤️ Thanks :)

**Comment by ayamir** [comment]
> @Jint-lzxy @ayamir I put your configuration in catppuccin/nvim here: https://github.com/catppuccin/nvim#previews
> 
> What do you think? :)

How you configure your `lueline`? It looks awesome:>

**Comment by nullchilly** [comment]
@ayamir It's the default catppuccin's feline integration 😅

**Comment by ayamir** [comment]
> 

all right:)

**Pull request merged**
