### PR TITLE
fix(catppuccin): Set global palette properly.

### PR DESCRIPTION
**Pull request by Jint-lzxy**
We still need `vim.g.catppuccin_flavour` to set the palette correctly

### CODE REVIEW

**Review by jczhang02 — APPROVED** [review]

**Comment by jczhang02** [comment]
Support! Great Job!

**Comment by nullchilly** [comment]
I think we should throw these palettes inside a function, like this

```lua
require("catppuccin").setup({
  color_overrides = {
    mocha = {
      cp.flamingo = "#F2CDCD"
    }  
  }
  highlight_overrides = {
    mocha = function(mocha)
      CursorLineNr = { fg = cp.green }
    end
  }
}
```

**Comment by nullchilly** [comment]
@Jint-lzxy Check it out! https://github.com/catppuccin/nvim#overwriting-highlight-groups

**Comment by Jint-lzxy** [comment]
@nullchilly The update has been adopted 👍 Thanks for the efforts in supporting function-style highlight overloading ❤️ The code is much simpler now!

**Comment by nullchilly** [comment]
@Jint-lzxy Can you do me a favour, I am looking for community screenshots here https://github.com/catppuccin/nvim/discussions/323 :)

**Review by ayamir — APPROVED** [review]

**Comment by Jint-lzxy** [comment]
Sure :) @nullchilly

**Pull request merged**
