### PR TITLE
chore: sort and patch

### PR DESCRIPTION
**Pull request by CharlesChiuGit**
1. clean up legacy code
2. sort things so it's better to review after
3. minor patched

### CODE REVIEW

**Comment by Jint-lzxy** [comment]
Ah this is great! The code looks _much_ more friendly to OCD 🤣

Just curious, what is `Suckless`?

**Comment by Jint-lzxy** [comment]
Ah this is great! The code looks _much_ more friendly to OCDs 🤣

Just curious, what is `Suckless`?

**Comment by CharlesChiuGit** [comment]
> The code looks _much_ more friendly to "OCDs" rofl

TBH, the sorting has been bugging for months. lol 
And since those sections haven't been touch in a while, I think it's find to "sort" it a bit lol.



> Just curious, what is `Suckless`?

It's a bit hard to give it a definition.
But I think u can get the idea from below links.
https://github.com/fabi1cazenave/suckless.vim
https://www.reddit.com/r/neovim/comments/ygkx1p/suckless_neovim_plugins/
https://www.libhunt.com/posts/948880-suckless-neovim-plugins

I think in short, it just a modest way to say "better". lol

**Review by Jint-lzxy — APPROVED** [review]
LGTM 🥞

**Pull request merged**
