### PR TITLE
feat(nvim-treesitter): add nvim-treesitter-context

### PR DESCRIPTION
**Pull request by Saafo**
close https://github.com/ayamir/nvimdots/discussions/693#discussioncomment-5802367

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
Don't we need to `require` it?

**Comment by CharlesChiuGit** [comment]
Also, this might need to set the highlightings in #699 as well.

**Comment by Saafo** [comment]
> Don't we need to `require` it? https://github.com/nvim-treesitter/nvim-treesitter-context#configuration

The default value is good enough to me, so we can just add to dependencies, not to require it.

> Also, this might need to set the highlightings in https://github.com/ayamir/nvimdots/pull/699 as well.

I've read this pr and I'm exciting to it! But I think it might out of this pr's scape since the highlighting pr is not merged yet.

**Comment by CharlesChiuGit** [comment]
> I've read this pr and I'm exciting to it! But I think it might out of this pr's scape since the highlighting pr is not merged yet thinking.

make sense.

**Review by CharlesChiuGit — COMMENTED** [review]
LGTM

**Pull request merged**
