### PR TITLE
chores: rearrange wm keymaps

### PR DESCRIPTION
**Pull request by AngelontheRoad**
I put wm keymaps into `keymap/ui.lua` and divided them into `builtin_map` and `plug_map`. It's strightfoward and maybe you could like it.

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
It make sense to me to move those `windows` core keymaps to `keymap/ui.lua`, but it would be even better if you move the remaining `edit` core keymaps to `keymap/editor.lua`.

Don't forgot to remove [this line](https://github.com/AngelontheRoad/nvimdots/blob/c3837041a995ed0c741db6b54ab99d39c288fb34/lua/core/init.lua#L107) and update `tutor/dots.tutor`!

**Review by ayamir — APPROVED** [review]
LGTM

**Comment by AngelontheRoad** [comment]
> It make sense to me to move those `windows` core keymaps to `keymap/ui.lua`, but it would be even better if you move the remaining `edit` core keymaps to `keymap/editor.lua`.
> 
> Don't forgot to remove [this line](https://github.com/AngelontheRoad/nvimdots/blob/c3837041a995ed0c741db6b54ab99d39c288fb34/lua/core/init.lua#L107), update `tutor/dots.tutor` and update wiki!

Right, I've done.

**Review by CharlesChiuGit — APPROVED** [review]
LGTM, also https://github.com/ayamir/nvimdots/wiki/Keybindings is updated.
ready to merge.

**Pull request merged**
