### PR TITLE
chore(settings): replace `pright` with `jedi_language_server`.

### PR DESCRIPTION
**Pull request by ayamir**
https://github.com/ayamir/nvimdots/discussions/708

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
can't really review the pr in a few weeks, my home pc just got blown up by a fking transformer accident around my house.

i need to buy a new pc 😰

**Comment by ayamir** [comment]
> can't really review the pr in a few days, my home pc just got blown up by a fking transformer accident around my house.
> 
> i need to buy a new pc 😰

Wish you all the best :)

**Comment by ayamir** [comment]
We'd better merge it before 3.0.0 released.

**Review by Jint-lzxy — APPROVED** [review]
LGTM

**Pull request merged**
