### PR TITLE
feat(utils): auto-refresh builtin palette on `ColorScheme`

### PR DESCRIPTION
**Pull request by Jint-lzxy**
This PR implemented dynamic palette support for https://github.com/ayamir/nvimdots/issues/698#issuecomment-1614699356.

cc @volpan

### CODE REVIEW

**Comment by volpan** [comment]
Then how can I use it in configs such as `lualine`?

**Comment by Jint-lzxy** [comment]
Just use it as usual. The only difference is each call to `get_palette` would now return a palette configured for the active colorscheme - the same as `require("catppuccin.palettes").get_palette()`.

**Comment by volpan** [comment]
Actually, if I use this in the autocmd `ColorScheme` (the same autocmd as util), it has a delay which means this can be applied in the next color-scheme change.

image

**Comment by volpan** [comment]
LGTM

**Review by volpan — APPROVED** [review]

**Review by ayamir — APPROVED** [review]

**Pull request merged**
