### PR TITLE
chore(catppuccin): Update compile fn.

### PR DESCRIPTION
**Pull request by Jint-lzxy**
> Ref: https://github.com/catppuccin/nvim/pull/289

### CODE REVIEW

**Comment by nullchilly** [comment]
autocmd and packer hook is no longer required

**Comment by Jint-lzxy** [comment]
@nullchilly Thanks for the heads up :)

**Comment by nullchilly** [comment]
I wanted to try this config out but the packer bootstrap seems broken?

image

**Comment by Jint-lzxy** [comment]
@nullchilly This is due to the original design pattern _(because the direct use of `git clone` in Mainland China will have "connection refused" as response in most cases, so @ayamir switched to ssh)_. More discussion at https://github.com/ayamir/nvimdots/issues/49 and [wiki](https://github.com/ayamir/nvimdots/wiki/Prerequisites). The error message `Host key verification failed` indicates that `ssh` is not configured correctly. Alternatively, I'm migrating the installation process to the direct use of an installation script to detect problems. I'm so sorry that this has troubled you.

I will add `git` installation method to the install script recently (similar issue: https://github.com/ayamir/nvimdots/issues/168). Current command:
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/0.8/install/install.sh)"
```

**Review by ayamir — APPROVED** [review]

**Pull request merged**
