### PR TITLE
BREAKING CHANGE: Catppuccin is upgraded to v0.2, but color palette is preserved (mocha)

### LINKED ISSUE #159: Update catppuccin to V0.2 (latest)?
## Describe the issue
Hi! First off - I love this set of configs, thanks for the great efforts 👍

Noticed that at commit https://github.com/ayamir/nvimdots/commit/2e72ca751cc567f9bb42f4b1541c42e1247298c3, you rolled back to previous version of catppuccin (I prefer original palette too（), but recently catppuccin has been updated very frequently, many bugs have been gradually fixed, and the project structure and configuration methods have both become clearer... So do you consider updating to the newest version (v2) and then manually set the color of the palette as well as the highlight of the corresponding integration? In this way, we can not only enjoy the functions and fixes brought by the latest version & commits, but also continue to use the previous color palettes. I'm currently working on it, and there should be a draft PR very soon~

_(There are many changes taking place. For specific implementation, please see the code detail below (although it hasn't been completed yet)_

**< Another issue is that bufferline's total number of LSP prompts _(errors, warnings, infos)_ on status bar is no longer in the default config in the new version. This can be fixed by adding the following lines in the setup table. If it is meant to be displayed, I can post a pr ~>**

```lua
diagnostics_indicator = function(count, level, diagnostics_dict, context)
	return "(" .. count .. ")"
end,
```
*****

## 描述问题

Hiii作者大大，首先非常感谢您的neovim配置！很好用👍

您在 https://github.com/ayamir/nvimdots/commit/2e72ca751cc567f9bb42f4b1541c42e1247298c3 的时候回滚到了catppuccin之前的版本（不过确实我也更喜欢之前的配色w），但最近catppuccin更新的特别频繁，许多bug都已被逐步修复，项目结构与配置方法也更加清晰了。。。所以您考不考虑更新到v2然后再自行设置调色板的颜色和对应集成的高亮？这样可以既享受最新版带来的功能和修复，也能继续用之前的配色（，我这边在一点点做，应该会在最近提一个draft pr~

_（不过要改的确实多，具体实现可以看看下面的正在施工的部分233（尽管还没弄好）_

**< 还有一个是bufferline.nvim状态栏上的lsp提示总数（错误、警告、提示）在新版不再是默认内容，可以通过在setup里添加下面这几行解决，如果确实是希望显示的话我可以提一个pr～ >**

```lua
diagnostics_indicator = function(count, level, diagnostics_dict, context)
	return "(" .. count .. ")"
end,
```

### Semifinished Product's Screenshot / 半成品截图

截屏2022-07-17 20 59 49

### Implementation Detail / 实现细节（半成品）

<details>
    <summary>Palette configs / 配色调整</summary>
<p>

```lua
color_overrides = {
	mocha = {
		rosewater = "#F5E0DC",
		flamingo = "#F2CDCD",
		mauve = "#DDB6F2",
		pink = "#F5C2E7",
		red = "#F28FAD",
		maroon = "#E8A2AF",
		peach = "#F8BD96",
		yellow = "#FAE3B0",
		green = "#ABE9B3",
		blue = "#96CDFB",
		sky = "#89DCEB",
		teal = "#B5E8E0",
		lavender = "#C9CBFF",
	},
},
```

<br />
</details>

<details>
    <summary>Plugin integrations hl configs / 插件集成配色调整</summary>
<p>

```lua
custom_highlights = {
	Comment = { fg = cp.overlay1 },
	LineNr = { fg = cp.overlay1 },
	CursorLine = { bg = cp.none },
	CursorLineNr = { fg = cp.lavender },
	DiagnosticVirtualTextError = { bg = cp.none },
	DiagnosticVirtualTextWarn = { bg = cp.none },
	DiagnosticVirtualTextInfo = { bg = cp.none },
	DiagnosticVirtualTextHint = { bg = cp.none },

	TSField = { fg = cp.rosewater },
	TSProperty = { fg = cp.yellow },

	TSInclude = { fg = cp.teal },
	TSOperator = { fg = cp.sky },
	TSKeywordOperator = { fg = cp.mauve },
	TSPunctSpecial = { fg = cp.maroon },

	TSConstructor = { fg = cp.lavender },
	TSException = { fg = cp.peach },

	TSConstBuiltin = { fg = cp.lavender },
	TSVariableBuiltin = { fg = cp.red, style = { "italic" } },

	TSFuncMacro = { fg = cp.red, style = {} },
	TSParameter = { fg = cp.rosewater },
	TSKeywordFunction = { fg = cp.maroon },
	TSKeywordReturn = { fg = cp.pink, style = {} },

	TSMethod = { style = { "italic" } },
	TSNamespace = { fg = cp.rosewater },

	TSPunctDelimiter = { fg = cp.teal },
	TSPunctBracket = { fg = cp.overlay2 },

	TSType = { fg = cp.yellow },
	TSVariable = { fg = cp.white },
	TSTagAttribute = { fg = cp.mauve },
	TSTag = { fg = cp.peach },
	TSTagDelimiter = { fg = cp.maroon },
	TSText = { fg = cp.text },

	bashTSFuncBuiltin = { fg = cp.red, style = { "italic" } },
	bashTSParameter = { fg = cp.yellow, style = { "italic" } },

	luaTSField = { fg = cp.lavender },
	luaTSConstructor = { fg = cp.flamingo },

	javaTSConstant = { fg = cp.teal },

	typescriptTSProperty = { fg = cp.lavender, style = { "italic" } },

	cssTSType = { fg = cp.lavender },
	cssTSProperty = { fg = cp.yellow, style = { "italic" } },

	cppTSProperty = { fg = cp.white },
},
```

<br />
</details>

### PR DESCRIPTION
**Pull request by Jint-lzxy**
Once finished and merged, this would close #159 

### Palettes
- ~Light _(a.k.a latte)_~ **pending**
- [x] Dark _(a.k.a mocha)_

### Integrations
- [x] Treesitter
- [x] Neovimbase
- [x] Editor
- [x] Syntax
- [x] Terminal
- [x] Dashboard
- [x] Indent_blankline
- [x] Lsp_trouble
- [x] Neogit
- [x] Nvimtree
- [x] Telescope
- [x] Bufferline
- [x] Gitsigns
- [x] Markdown
- [x] Symbols_outline
- [x] Which_key
- [x] Cmp
- [x] Fern
- [x] Hop
- [x] Lsp_saga
- [x] Native_lsp
- [x] Notify
- [x] Ts_rainbow
- [x] Dapui

### What is the current state of this PR?
- This PR is currently a **draft**. It cannot be merged until being marked as ready for review.

#### How come?
- In this way, the latest progress of the changes can be tracked.

### When will this PR be marked as ready for review?
- There are many changes needed to take place _(mostly integration stuffs)_, and we also need to consider readability, efficiency (startup time), final effects and other factors. Probably next month?

### What files _(or lines)_ will be changed?
- The changes will all be made inside `lua/modules/ui/config.lua`, a tiny exception is for dapui (at `lua/modules/editor/config.lua`), since we need to override nvim-dap's default highlight groups, AFTER requiring nvim-dap.

#### Then, what features will be changed / added? Can you talk about this more in detail?
1. Catppuccin is upgraded to v0.2
2. The colors for `mocha` is being modified to previous v0.1 one. I choose `mocha` because it has the FEWEST changes in colors.
3. The integrations that catppuccin would affect (a.k.a. highlight groups) would be modified as far as I can to make it look like the original one.
4. Settings are changed to make catppuccin work correctly. (See https://github.com/catppuccin/nvim/issues/178 for details)

#### Code details?
1. Color changes are taken place inside the `color_overrides` table.
2. Integration changes are taken place inside the `highlight_overrides` table.
3. See the actual code for misc changes.

### Looks like there're many additions, will it affect performance?
- Currently, there's only a negligible change in performance. But if it would cause an impact in future changes, I will try my best to solve it :).

### Any other notes?
- When the PR is making some step forward, I will post a comment that can help you understand what's happening behind the scene!
- If you have any questions regarding the changes _(or other stuffs)_, feel free to post a comment! I'll try my best to answer it!

### CODE REVIEW

**Comment by nullchilly** [comment]
@Jint-lzxy Heya, maintainer of catppuccin here, I saw your pr and thought it would be a good idea to include per flavour custom highlights: https://github.com/catppuccin/nvim#overwriting-highlight-groups

Here is a sneak peak, hope this is useful to you 👍🏻 

```lua
local ucolors = require "catppuccin.utils.colors"
local latte = require("catppuccin.palettes").get_palette "latte"
local frappe = require("catppuccin.palettes").get_palette "frappe"
local macchiato = require("catppuccin.palettes").get_palette "frappe"
local mocha = require("catppuccin.palettes").get_palette "mocha"

vim.g.catppuccin_flavour = "macchiato"
local colors = require("catppuccin.palettes").get_palette() -- return vim.g.catppuccin_flavour palette

require("catppuccin").setup {
	highlight_overrides = {
		all = {
			CmpBorder = { fg = "#3e4145" },
		},
		latte = {
			Normal = { fg = ucolors.darken(latte.base, 0.7, latte.mantle) },
		},
		frappe = {
			TSConstBuiltin = { fg = frappe.peach, style = {} },
			TSConstant = { fg = frappe.sky },
			TSComment = { fg = frappe.surface2, style = { "italic" } },
		},
		macchiato = {
			LineNr = { fg = macchiato.overlay1 }
		},
		mocha = {
			Comment = { fg = mocha.flamingo },
		},
	},
}
```

**Comment by Jint-lzxy** [comment]
Thanks @nullchilly :) Great suggestion 👍

btw, thank you for the great efforts in offering us this gorgeous theme! Recent changes have made it even more intuitive and easier to use!

**Comment by jczhang02** [comment]
Hey, @Jint-lzxy , your efforts for integrating the theme into nvimdots is fantastic! Hope it will be finished quickly! I can't wait to use the new version theme.

**Comment by Jint-lzxy** [comment]
Thanks @jczhang02 :)

I was testing base hl configs for nvim itself recently, which involves modification of various colors and adjustment for v0.2's new highlight groups _(so that they won't conflict with old hls_), but everything is still on track! I'll finish this asap 👍

**Comment by Jint-lzxy** [comment]
@ayamir 可以帮忙先测试和review一下嘛\~（康康有啥问题），现在绝大多数的更改都已经完成啦
- ssh: `git clone git@github.com:Jint-lzxy/nvimdots.git`
- https: `git clone https://github.com/Jint-lzxy/nvimdots.git`
- github CLI: `gh pr checkout 163`

**建议先不要merge，还有一些细枝末节的更改和确认没做\~**

启动时间在我的配置下没有很大的变化（甚至还快了些，因为catppuccin优化了项目结构），使用`:CatppuccinCompile`经过测试可以更快地完成加载（设置catppuccin的时间在\~3ms左右，能节省\~15ms的时间），数据存在`$HOME/.cache/nvim/catppuccin`目录下，但更改过设置后需要重新编译（\*这些说明最后会写一个doc的～）

### 一些问题
- **这些更改应该都需要写doc（例如关于编译），您建议放到哪里？**
- 在我这里测试的配置有些不同，应该需要在您那边也测试一遍（例如搜索，替换，看状态栏的颜色，bufferline有没有颜色不协调这些日常使用中会经常碰到的）
- ~好像还有但突然忘记了2333想起来了再加~

### Q&A
- Q: 为什么要有下面这个函数？
```lua
local function getModifiedPalette()
```
- A: 因为我们在覆盖高亮组 _（也即获取调色板）_ 的时候对mocha的颜色做出的更改还**没有**被真正写入，而在仅调用一次`setup`的情况下，我们传入的颜色已经被解析了（例如，`cp.pink -> "#F5C2E7"`），所以完全不可能获得更改后的调色板，因此需要手动设置。

- Q: 这次都改了些啥？
- A: 这次仅仅修改了`mocha`这个调色板的设置。其余的配色均没有触及，切换的话会**仍然**是未更改的配色，这是**有意为之**的。同时还修改了对`DAP`的集成的配色（见注释），以及一些其他参数的更改（例如传入数据要用表了）

- Q: 对亮色调色板的支持？
- A: 对`latte`目前还没有做出调整（因为现有配色无法直接移植到亮色背景下，会有冲突，这估计也是catppuccin改集成的原因（？）），但如果确实需要会继续去实现的\~。（之前我记得catppuccin好像也没有亮色调色板）目前还是建议使用一些专门用于亮色背景下的配色\~

- Q: 有没有调色板的成品照片？
- A: 当然有啦！而且对mocha的配色有了一些较大的调整（v0.2的色调偏黑了，应该是混合过），详见：
截屏2022-08-08 08 36 14

- Q: 有没有成品截图？
- A: 有，在这！
LW
LW2

- Q: 有没有前后对比图？
  - A: 有，都准备好啦！
  - v0.1: 
original
  - Current:
current

**Comment by jczhang02** [comment]
很棒的pr! 我也会去测试一到两天，看看有什么问题没有。
另外，对于您说的问题，有一些可能的回复：

- doc的话也许放到wiki中一个新的章节或者use directly中会较好；
- 数字如果设置italic可能会有观感问题，可以bold或者维持现状。

**Comment by Jint-lzxy** [comment]
@ayamir @jczhang02 I plan to add a hook that could automatically compile Catppuccin when Packer compiles, so as to avoid unnecessary issues. What's your opinion? / 我打算加一个`:PackerCompile`时自动编译Catppuccin的钩子，这样的话会少很多不必要的issue，你们觉得如何？

Code:
```lua
vim.api.nvim_create_autocmd("User", {
	pattern = "PackerCompileDone",
	callback = function()
		vim.cmd "CatppuccinCompile"
		vim.defer_fn(function()
			vim.cmd "colorscheme catppuccin"
		end, 0) -- Defered for live reloading
	end
})
```

**Review by jczhang02 — APPROVED** [review]
Fantastic work! I reviewed commits and set to normal comment wait for @ayamir 's review.

**Comment by ayamir** [comment]
The appearance is ok, I can't differ the old one with this.
+ About the doc of recompilation, I prefer to add it to wiki and use command hook both.
+ About the number's appearance, it's suitable so no need to set it to `bold` or `italic`.
Thanks for your great PR, I will merge it.

**Review by ayamir — APPROVED** [review]

**Comment by Jint-lzxy** [comment]
@ayamir We're all set 👍 

- The auto-compile hook is implemented inside `lua/core/init.lua` to avoid creating `autocmd` every time we compile catppuccin.
- Doc will be completed soon!

**Comment by nullchilly** [comment]
@Jint-lzxy This is also an option:

```lua
local packer = vim.api.nvim_create_augroup("Catppuccin", { clear = true })

vim.api.nvim_create_autocmd("User", {
	group = packer,
	pattern = "PackerCompileDone",
	callback = function()
		require("catppuccin").compile()
		vim.defer_fn(function() vim.cmd "colorscheme catppuccin" end, 0)
	end,
})
```

**Comment by Jint-lzxy** [comment]
Thanks @nullchilly 👍

**Pull request merged**
