### PR TITLE
fix(gitsigns): upstream breaking changes

### PR DESCRIPTION
**Pull request by Jint-lzxy**
See https://github.com/lewis6991/gitsigns.nvim/commit/3d7e49c201537ee0293a1a3abe67b67f8e7648a5

---

Created with `gh pr create`

### CODE REVIEW

**Review by ayamir — APPROVED** [review]

**Comment by yinghaoyu** [comment]
Opening nvim show tips with `'signs.add.hl' is now deprecated, please define highlight 'GitSignsAdd'`，how can i fix it?

**Comment by ayamir** [comment]
> Opening nvim show tips with `'signs.add.hl' is now deprecated, please define highlight 'GitSignsAdd'`，how can i fix it?

switch to 0.10 branch and `git pull`

**Comment by yinghaoyu** [comment]
https://github.com/zbirenbaum/neodim/issues/46

**Comment by ayamir** [comment]
> [zbirenbaum/neodim#46](https://github.com/zbirenbaum/neodim/issues/46)

`:Lazy sync` to update your neodim to latest version.

**Pull request merged**
