### PR TITLE
feat(ui)!: unify other UI components

### PR DESCRIPTION
**Pull request by volpan**
Need modifications

cc @Jint-lzxy

### CODE REVIEW

**Comment by Jint-lzxy** [comment]
ssc

cc @volpan

**Comment by volpan** [comment]
LGTM (u're really such a nvim super man :exploding_head:

**Review by ayamir — APPROVED** [review]
LGTM 👍

**Review by CharlesChiuGit — APPROVED** [review]
This looks nice!
LGTM!

**Pull request merged**
