### PR TITLE
fix: untrack changes in lua/user/ after installation.

### PR DESCRIPTION
**Pull request by ayamir**
Add a step after installation to make git `skip-worktree` from `user` dir.
For users already using, execute the command manually:
Windows:
```powershell
cd ~/AppData/Local/nvim
@(git ls-files lua/user) | ForEach-Object {&"git" update-index --skip-worktree $_}
```
*nix:
```shell
cd ~/.config/nvim
git ls-files -z lua/user/ | xargs -0 git update-index --skip-worktree
```
More info about `assume-unchanged` and `skip-worktree`: https://stackoverflow.com/questions/13630849/git-difference-between-assume-unchanged-and-skip-worktree

@popjdh

### CODE REVIEW

**Review by CharlesChiuGit — APPROVED** [review]
Can confirm it works on macos.

**Comment by popjdh** [comment]
Just now, I changed `lua/user` to `lua/user_template` through `git mv`. And also modified the installation script to automatically generate `lua/user`.

This is the [PR #986](https://github.com/ayamir/nvimdots/pull/986) I submitted after modification.

**Comment by ayamir** [comment]
@popjdh I prefer this way to do the same thing instead of introducing template files due to redundancy.
Besides, using command to ignore won't influence current users who already customized their configs.

**Comment by popjdh** [comment]
> @popjdh I prefer this way to do the same thing instead of introducing template files due to redundancy. Besides, using command to ignore won't influence current users who already customized their configs.

1. For some users who use local branch to manage configurations, `git --skip-worktree` will disrupt their management
2. When modifying the preset `lua/user`, it is necessary to first `git --no-skip-worktree` before merging conflicts. Unless the preset is never changed, the consequences are equally cumbersome.

**Comment by popjdh** [comment]
> @popjdh I prefer this way to do the same thing instead of introducing template files due to redundancy. Besides, using command to ignore won't influence current users who already customized their configs.

In addition, for users who have already updated to the latest version, it is not a difficult problem to backup using methods such as "cp", "tar", etc😘

**Comment by ayamir** [comment]
> > @popjdh I prefer this way to do the same thing instead of introducing template files due to redundancy. Besides, using command to ignore won't influence current users who already customized their configs.
> 
>     1. For some users who use local branch to manage configurations, `git --skip-worktree` will disrupt their management
> 
>     2. When modifying the preset `lua/user`, it is necessary to first `git --no-skip-worktree` before merging conflicts. Unless the preset is never changed, the consequences are equally cumbersome.

You are correct, close it.

**Pull request closed without merging**
