### PR TITLE
fix(script-win): Avoid prompting for user input when failed

### PR DESCRIPTION
**Pull request by Jint-lzxy**
This should eliminate that weird message showing:
```console
cmdlet prompt at command pipeline position 1

Supply values for the following parameters:
Msg:
```

@ayamir @CharlesChiuGit  I would be most grateful if you could test this fix _(let the program exit abnormally, calling `_abort`)_

### CODE REVIEW

**Comment by ayamir** [comment]
No help currently:
image

**Comment by CharlesChiuGit** [comment]
I think @Jint-lzxy need us to edit the script a bit like:
```ps1
...

	_abort -Msg "test"
	Ring-Bell
	Wait-For-User
```

**Comment by Jint-lzxy** [comment]
@ayamir It is intentional to issue such prompt when directly sending `SIGABRT` to terminate the script. _(This forces the user to close this window to clean up orphan processes, as we do not want them to continue executing the install script in this session)_.

One approach is to press keys other than `RETURN` when prompting for confirmation:
https://github.com/ayamir/nvimdots/blob/24f89efa6f8a19e3db5fba9c3cf2d09c1f2b9621/install/install.ps1#L73-L81

**Comment by CharlesChiuGit** [comment]
I edited the file like this:
```ps1
...
	if ((Test-Path $env:CCDEST_DIR)) {
		warn -Msg "The destination folder: `"$env:CCDEST_DIR`" already exists."
		warn-Ext -Msg "We will make a backup for you at `"$env:CCBACKUP_DIR`"."
	}

	_abort -Msg "test" -Type "NotInstalled" -----> add this line
	Ring-Bell
	Wait-For-User
...
```
And the result:
圖片

If I understand correctly, I think this PR is working as expected.

**Comment by ayamir** [comment]
> @ayamir It is intentional to issue such prompt when directly sending `SIGABRT` to terminate the script. _(This forces the user to close this window to clean up orphan processes, as we do not want them to continue executing the install script in this session)_.
> 
> One approach is to press keys other than `RETURN` when prompting for confirmation:
> 
> https://github.com/ayamir/nvimdots/blob/24f89efa6f8a19e3db5fba9c3cf2d09c1f2b9621/install/install.ps1#L73-L81

If so, it's ok.

**Review by ayamir — APPROVED** [review]

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy Actually, `ripgrep` is not being check by the script lol.

圖片

**Comment by ayamir** [comment]
One question, can you install these packages successfully without administrator privilege?

**Comment by CharlesChiuGit** [comment]
> One question, can you install these packages successfully without administrator privilege? I need to remind windows users in readme if so.

If u use `scoop`, then admin-previlege is not needed.
I'm not sure about choco tho, but to my understanding users need extra settings to install non-admin-previledge choco.

**Comment by ayamir** [comment]
`choco` need it.

**Pull request merged**
