### PR TITLE
Use cmp-cmdline and illuminate to improve the use experience

### PR DESCRIPTION
**Pull request by feng2r200**
These two plugins are written in Lua and have good compatibility with CMP and LSP. They provide more accurate completion and highlighting, and do not affect the use experience when large files are used

### CODE REVIEW

**Comment by flaviusbuffon** [comment]
Wondering the reason for using plugin cmp-cmdline instead of wilder?

**Comment by feng2r200** [comment]
> Wondering the reason for using plugin cmp-cmdline instead of wilder?

Personally, I think that in practical use, the implementation of incomplete command line functions is similar, but CMP CmdLine is based on CMP, which has better compatibility, less code and better stability. In addition, it can obtain the support of other CMP plug-ins by adding source.And I personally prefer to use fewer plug-ins, because more plug-ins and more file scanning. VIM does not respond well when opening large files of large projects, so I will try to simplify the plug-ins as much as possible (my company project has a lot of large Java code, and the redrawing page will get stuck). CMP CmdLine is also a pull request I decided to launch after a long time. May I know why you like Wilder? I'll take the time to look at their code and learn more about it

**Comment by ayamir** [comment]
A new bug: https://www.reddit.com/r/neovim/comments/ucze6k/q_any_idea_why_i_cannot_do_tab_completion_on/
So I will roll back to wilder util it is fixed.

**Comment by feng2r200** [comment]
> A new bug: https://www.reddit.com/r/neovim/comments/ucze6k/q_any_idea_why_i_cannot_do_tab_completion_on/
> So I will rollback to wilder util it fixed.

I saw this. I also encountered this problem some time ago, but now there is no such problem.At least I can't reproduce this problem for now.

**Comment by flaviusbuffon** [comment]
I have also encountered this problem, and I believe the reasons are as follows. cmp-cmdline depends on nvim-cmp to work, and nvim-cmp sets event = "InsertEnter", so you have to return to command mode after editing to achieve command completion.
The reddit post just noticed it can not used in command mode sometimes, but may be dismissed the essence of this plugin.

Also, that is a reason for why I want to use wilder instead of cmp-cmdline.

**Comment by feng2r200** [comment]
> I have also encountered this problem, and I believe the reasons are as follows. cmp-cmdline depends on nvim-cmp to work, and nvim-cmp sets event = "InsertEnter", so you have to return to command mode after editing to achieve command completion. The reddit post just noticed it can not used in command mode sometimes, but may be dismissed the essence of this plugin.
> 
> Also, that is a reason for why I want to use wilder instead of cmp-cmdline.

I see. I'll switch my configuration to wilder and follow up their repostories

**Comment by flaviusbuffon** [comment]
> > I have also encountered this problem, and I believe the reasons are as follows. cmp-cmdline depends on nvim-cmp to work, and nvim-cmp sets event = "InsertEnter", so you have to return to command mode after editing to achieve command completion. The reddit post just noticed it can not used in command mode sometimes, but may be dismissed the essence of this plugin.
> > Also, that is a reason for why I want to use wilder instead of cmp-cmdline.
> 
> I see. I'll switch my configuration to wilder and follow up their repostories

I think it can not be viewed as a problem carried by `cmp-cmdline`, which is inevitable! May be you can try to solve this problem by change `nvim-cmp` trigger `event `setting. But please be carefully since the dependencies and event handling of `packer` are not very well done

**Comment by feng2r200** [comment]
> > > I have also encountered this problem, and I believe the reasons are as follows. cmp-cmdline depends on nvim-cmp to work, and nvim-cmp sets event = "InsertEnter", so you have to return to command mode after editing to achieve command completion. The reddit post just noticed it can not used in command mode sometimes, but may be dismissed the essence of this plugin.
> > > Also, that is a reason for why I want to use wilder instead of cmp-cmdline.
> > 
> > 
> > I see. I'll switch my configuration to wilder and follow up their repostories
> 
> I think it can not be viewed as a problem carried by `cmp-cmdline`, which is inevitable! May be you can try to solve this problem by change `nvim-cmp` trigger `event `setting. But please be carefully since the dependencies and event handling of `packer` are not very well done

Thanks. I have found the reason why I have no problems here. A very important content has been omitted from the code I submitted, which is mentioned above

image

The event was not changed when submitting

**Pull request merged**
