### PR TITLE
fix(lua_ls): use `luarc.json` for server config

### PR DESCRIPTION
**Pull request by Jint-lzxy**
Ref: https://github.com/ayamir/nvimdots/issues/899#issuecomment-1653926046

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
Nice! Now only one `lua_ls` process is running!
圖片

**Comment by Jint-lzxy** [comment]
Ah, I remember why I didn't port this upstream. The issue is in order to enable Neovim API completion, users now need to add the library themselves:
```lua
    "library": [
      "/path/to/share/nvim/runtime/lua",
      "/path/to/share/nvim/runtime/plugin"
    ]
```
See [lua-language-server/FAQ#why-are-there-two-workspacesprogress-bars](https://github.com/LuaLS/lua-language-server/wiki/FAQ#why-are-there-two-workspacesprogress-bars).

**Comment by CharlesChiuGit** [comment]
hmmm, that's tricky one. Maybe we need to modify install scripts for this part?

**Comment by Jint-lzxy** [comment]
> hmmm, that's tricky one. Maybe we need to modify install scripts for this part?

IMO We can just leave it as-is. Looks like the FAQ got updated recently - this is likely not a problem though, since `lua_ls` will actually index every file only once. It just creates an illusion that two workspaces have been setup.

**Comment by CharlesChiuGit** [comment]
nice, that would save is some hustle!

**Pull request closed without merging**
