### PR TITLE
feat: add plugin zeioth/garbage-day.nvim.

### PR DESCRIPTION
**Pull request by jczhang02**
Not sure the impact of the plugin. Maybe have a discussion?

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
What's the difference between https://github.com/hinell/lsp-timeout.nvim and https://github.com/Zeioth/garbage-day.nvim?
I cant really tell the advantages from both of it's doc.

**Comment by jczhang02** [comment]
you are right! My mistake! I will close this pr.

**Comment by CharlesChiuGit** [comment]
What? XDDD
We haven't adopt one of those yet, but i think it's nice to have sth similar.
i just want to know which one is better lol

**Comment by jczhang02** [comment]
I mean that i will use this plugin and test the two plugins lol.

**Comment by CharlesChiuGit** [comment]
ah, ok lol.
than i'll close the pr for now.

**Pull request closed without merging**
