### PR TITLE
style: add single border for all of floating windows.

### PR DESCRIPTION
**Pull request by ayamir**

### CODE REVIEW

**Comment by ayamir** [comment]
I added single border for `telescope`, `LspInfo`, `PackerSync` and cmp window for documentation to make them easy to distinguish with code and keep consistency. How do you feel about this style? Let me know:)
@Jint-lzxy @ClSlaid @jczhang02 @CharlesChiuGit

**Comment by CharlesChiuGit** [comment]
I think it's great! I personally add double border and use a plugin called [tint.nvim](https://github.com/levouh/tint.nvim) to distinguish the floating windows. Just for reference.

**Comment by jczhang02** [comment]
It's great!

**Review by jczhang02 — APPROVED** [review]

**Review by Jint-lzxy — APPROVED** [review]
LGTM 🍉

**Pull request merged**
