### PR TITLE
fix(provider): leave provider specifications to user

### PR DESCRIPTION
**Pull request by misumisumi**
#886

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
the pr should done it's job, but i wonder if their's a better approach to it.

**Comment by Jint-lzxy** [comment]
> but i wonder if their's a better approach to it

The workaround that crossed my mind is to allow users to define their custom Python provider(s) _(which may include command-line options)_. But I'm not sure if this is feasible cause I rarely use Python-related stuffs

**Comment by misumisumi** [comment]
At least in NxOS, it is difficult to know the exact configuration of the latest neovim from outside of nix, since the product is managed as a hash.

**Comment by fecet** [comment]
I use python everyday but I use conda to manage envs so just respect `which python` works fine for me.

Another approach is to respect the settings in `poetry` (or similar thing) like https://github.com/vsedov/nvim/blob/master/lua/modules/lsp/lsp/providers/python/pylance.lua

**Comment by misumisumi** [comment]
The focus of the issue I was thinking about was about NixOS.
I did not consider other python environments such as poetry.
Therefore, I would like to raise the PullReqesut again, not on the issue of changing python_host_prog, but on the issue of NixOS support.
The title of the issue will be changed.

**Comment by Jint-lzxy** [comment]
So to summarize, is it feasible to directly use the exec `python` provided by `vim.fn.exepath`?

**Comment by misumisumi** [comment]
> So to summarize, is it feasible to directly use the exec python provided by vim.fn.exepath?

It can be used if it contains the necessary libraries for python such as global or `conda` or `venv`.
If not, NixOS requires `python(3)_host_prog` to be set correctly.
Because the `python` provided by `vim.fn.exepath` is user-wide python and does not contain the libraries neovim uses.
The environment containing the necessary libraries for neovim is provided by the command `nvim-python3`.

**Comment by Jint-lzxy** [comment]
IMO in this case we can just leave it alone, cause if this option is `nil` Neovim would use the fallback (i.e., the one on `$PATH`) if it exists.

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/887/commits/fb17e95a323deba45850200d0f311f40d65cb19f

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Review by ayamir — APPROVED** [review]

**Pull request merged**
