### PR TITLE
feat(ibl): more language nodes

### PR DESCRIPTION
**Pull request by Jint-lzxy**
As per https://github.com/ayamir/nvimdots/issues/1283#issuecomment-2161977122.

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
ref: https://github.com/nvim-treesitter/nvim-treesitter/tree/master/queries

**Comment by CharlesChiuGit** [comment]
i add this https://github.com/ayamir/nvimdots/blob/0e5145ddb3649ad050991ef0f30073676466be57/lua/modules/configs/ui/indent-blankline.lua#L142 since i think sometimes i'll start with closing tag. lol

it could be remove if it's not appropriate.

**Review by CharlesChiuGit — APPROVED** [review]
lgtm

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit I think u also need to check for any potential duplicates lol we've already got some defined in [`scope_languages.lua`](https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/lua/ibl/scope_languages.lua).

**Comment by CharlesChiuGit** [comment]
yeah, i had checked!

**Comment by Jint-lzxy** [comment]
> yeah, i had checked!

Holy shit these language tables are really messing with my head now lol my bad for the discombobulation!

**Comment by CharlesChiuGit** [comment]
> Holy shit these language tables are really messing with my head now lol my bad for the discombobulation!

lol, not at all! I totally can feel that and respect u for doing the PR, i spent almost one hour just to get those new nodes in. 🫠🫡🫡🫡

**Review by CharlesChiuGit — APPROVED** [review]
lgtm

**Comment by Jint-lzxy** [comment]
> lol, not at all! I totally can feel that and respect u for doing the PR, i spent almost one hour just to get those new nodes in. 🫠🫡🫡🫡

loll thx :) Also, pretty nice job here! Treesitter nodes are _always_ a hot mess lmao

**Pull request merged**
