### PR TITLE
chore(tsserver): support typescript-language-server

### PR DESCRIPTION
**Pull request by lcoder**
这个PR还有点问题，我想支持下tsserver，但是按我自己的配置，一直提示
image

看了下lsp info
image

想看看怎么改下

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
please mark this pr as draft

**Comment by CharlesChiuGit** [comment]
also @ayamir might not agree to add this lsp in this config.

**Comment by Jint-lzxy** [comment]
You shouldn't open a PR for this. Creating a new issue and adding a link to the diff between your repo and this repo would be better. Closing as we are against supporting _each and every_ language servers in the base config.

**Comment by Jint-lzxy** [comment]
Transferred: https://github.com/ayamir/nvimdots/issues/710

**Pull request closed without merging**
