### PR TITLE
fix(icons)!: update icon codepoints

### LINKED ISSUE #439: Update icon codepoints
[Release v2.3.3 · ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3)
> **Material Design Icons**
>
> The Material Design Icons have to move codepoints. Historically we patch them in between `F500` - `FD46`; but part of that range is needed for Chinese and other glyphs ... Their new home will be after `F0001`. And they grow considerably.
>
> The `v2.3.x` release has both, the 'old' and the 'new' codepoints to enable you an easier transision. **Please change** already **now** your prompts and other uses to the new codepoints. Release `v3.0.0` will finally drop the old codepoints (`F500` - `FD46`).

Compatibility of all icons will be checked after implementing #394.

### PR DESCRIPTION
**Pull request by Jint-lzxy**
Fixes #439. This PR will be marked as ready for review when nerd font v3.0.0 is released - now Material Design Icons still have some display problems.

Searched using `/[\uf500-\ufd46]`.

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy Is this PR ready to merge?

**Comment by Jint-lzxy** [comment]
> This PR will be marked as ready for review when nerd font v3.0.0 is released.

@CharlesChiuGit It's a WIP in upstream repo.

**Comment by CharlesChiuGit** [comment]
https://github.com/loichyan/nerdfix

**Comment by CharlesChiuGit** [comment]
it's finally here!

https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit @ayamir So here's the deal: Given that the default icons used by upstream repos will (probably) be replaced with `nf-cod-*` (codeicons), shall we also update `icons.lua` to keep consistency with theirs?

Ref:
https://github.com/nvim-tree/nvim-web-devicons/pull/264
https://github.com/onsails/lspkind.nvim/pull/64

**Comment by CharlesChiuGit** [comment]
i'll look into that after i hot home

**Comment by Jint-lzxy** [comment]
> quick question: can cod icons displayed without installing codicons.ttf?

Yes as they're part of the NF collection.

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/447/commits/c5da797bda96e9a423579281b9e0fcffc89763cf simply ran `nerdfix` without making any special adjustments:
```sh
find ./lua -type f -exec $TMPDIR/gh/unk1/bin/nerdfix fix --replace nf-mdi-,nf-md- {} \;
```

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit @ayamir So here's the deal: Given that some of the default icons used by upstream repos will (probably) be replaced with `nf-cod-*` (codeicons), shall we also update `icons.lua` to keep consistency with theirs?
> 
> Ref: [nvim-tree/nvim-web-devicons#264](https://github.com/nvim-tree/nvim-web-devicons/pull/264) [onsails/lspkind.nvim#64](https://github.com/onsails/lspkind.nvim/pull/64)

Seems legit. agreed.

**Comment by Jint-lzxy** [comment]
Looks like upstream repos decided to use Material Design Icons. So this PR is good 👍 A new release (v3.0.0) will be published after merging to remind users to update their installed Nerd Fonts.

**Comment by Jint-lzxy** [comment]
[\[View draft release\]](https://github.com/ayamir/nvimdots/releases/edit/untagged-e24ed49e08737a10a7d0)

**Comment by AngelontheRoad** [comment]
New icons is weird after I replace the old `icons.lua` with `icons.lua` here. The font I use is the new nerd font `JetBrainsMono Nerd Font`

**Comment by Jint-lzxy** [comment]
@AngelontheRoad [init.lua\#diff](https://github.com/ayamir/nvimdots/pull/447/files#diff-0fc5c43f6f1d7605fd7d16c088ba6b83f096eee8e2049517407bbaa27aa3a4f7). You have **"icons with incorrect size"**.

**Comment by AngelontheRoad** [comment]
> @AngelontheRoad [init.lua#diff](https://github.com/ayamir/nvimdots/pull/447/files#diff-0fc5c43f6f1d7605fd7d16c088ba6b83f096eee8e2049517407bbaa27aa3a4f7). You have **"icons with incorrect size"**. Quoting the release note:
> 
> > * **Starting from v3.0.0, please use the `Mono` variant (Nerd Font Mono _or_ NFM) as your GUI font.**

I tried some `NFM` font, but it not works.

**Comment by Jint-lzxy** [comment]
> I tried some `NFM` font, but it not works.

In fact it _is_ working, those undefined icons you observe is b/c https://github.com/nvim-tree/nvim-web-devicons/pull/264 hasn't _yet_ been merged. btw some Nerd Fonts have rendering issues when they're used in terminal emulators, you can use the `Prompo *` variant or another GUI font.

**Comment by AngelontheRoad** [comment]
> > I tried some `NFM` font, but it not works.
> 
> In fact it _is_ working, those undefined icons you observe is b/c [nvim-tree/nvim-web-devicons#264](https://github.com/nvim-tree/nvim-web-devicons/pull/264) hasn't _yet_ been merged. btw some Nerd Fonts have rendering issues when they're used in terminal emulators, you can use the `Prompo *` variant or another GUI font.

Thanks for your reply! I'd like to use old nerd font until all preparations done.

**Review by ayamir — APPROVED** [review]
LGTM

**Comment by CharlesChiuGit** [comment]
sorry that i couldn't review this, my pc is down right now due to a transformer accident.

**Comment by Jint-lzxy** [comment]
> sorry that i couldn't review this, my pc is down right now due to a transformer accident.

@CharlesChiuGit Sorry I just noticed that (https://github.com/ayamir/nvimdots/pull/713#issuecomment-1537069515). No worries! 've crossed my fingers for you 🍻

**Comment by yyb196** [comment]
@Jint-lzxy how can I disable this material icon. in my using case, it just render like a mess.

mosh-client ---remote connect---> server(include mosh-server tmux nvim)

after update to recent version, some characters randomly left on screen as below picture shows. I need a way to disable this feature I think, help please.

image

**Comment by Jint-lzxy** [comment]
> after update to recent version, some characters randomly left on screen as below picture shows

@yyb196 This should be a problem with your terminal - it probably failed to perform a full-screen redraw when Neovim requested it to do so. Can you reproduce this issue on another emulator?

**Comment by yyb196** [comment]
@Jint-lzxy thanks for your reponse. 

yes, I can reproduce it on iterm2, alacritty and kitty, and on iOS devices I can reproduce it on blink.

If I change to use ssh instead of mosh it works on all above terminal emulator.

I know its a bug of mosh protocol, but I need to develop on my macbook or my ipad using mosh connect to remote server, If I use ssh the connection randomly close if I move or switch app on my ios.
https://github.com/mobile-shell/mosh/issues/1041

Maybe we could find all the icons which using new codepoint and add a swtich to replace it with old codepoint?

**Comment by Jint-lzxy** [comment]
> Maybe we could find all the icons which using new codepoint and add a swtich to replace it with old codepoint?

@yyb196 Sorry I didn't quite get ur point. If I read this right, those "observations" do share the same root cause - ur shell (or protocol) doesn't support certain escape sequences, but ur terminfo database reports that they're actually supported - that's why u get random characters (that are part of such escape sequences which are left unprocessed). What leads u to think that this is caused by codepoint changes?

**Pull request merged**
