### PR TITLE
chore(plugins): update plugins with maintained fork.

### PR DESCRIPTION
**Pull request by ayamir**
#847
cc @Jint-lzxy @CharlesChiuGit @fecet @boomker

### CODE REVIEW

**Review by Jint-lzxy — APPROVED** [review]
LGTM 🍊

**Comment by boomker** [comment]
支持👍

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Comment by fecet** [comment]
Should we also remove rainbow in `nvim-treesitter.configs`?

**Comment by Jint-lzxy** [comment]
@fecet https://github.com/ayamir/nvimdots/commit/381f8fb2d3055be3791b9839daa929eb2a7e08b7

**Pull request merged**
