### PR TITLE
feat: Large file support

### LINKED ISSUE #338: Ability to edit large files
### Neovim version

NVIM v0.8.0 LuaJIT 2.1.0-beta3

### Operating system/version

Centos8

### Terminal name/version

iterm2

### $TERM environment variable

_No response_

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

当我打开一个大小为41M的日志文件的时候就会卡住很久，而且打开完成后对这个文件进行操作的时候也非常卡顿，想请教下大佬该如何解决这个问题

用--startuptime 打开日志的报告
====================================
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
000.088  000.082: event init
000.176  000.088: early init
000.327  000.151: locale set
000.358  000.031: init first window
000.605  000.247: inits 1
000.613  000.008: window checked
000.616  000.003: parsing arguments
000.981  000.055  000.055: require('vim.shared')
001.069  000.039  000.039: require('vim._meta')
001.070  000.087  000.048: require('vim._editor')
001.072  000.167  000.025: require('vim._init_packages')
001.073  000.291: init lua interpreter
001.115  000.042: expanding arguments
001.156  000.041: inits 2
001.479  000.323: init highlight
001.480  000.001: waiting for UI
002.212  000.732: done waiting for UI
002.232  000.019: init screen for UI
002.381  000.149: init default mappings
002.399  000.018: init default autocommands
002.933  000.055  000.055: sourcing /usr/share/nvim/runtime/ftplugin.vim
003.036  000.029  000.029: sourcing /usr/share/nvim/runtime/indent.vim
003.087  000.026  000.026: sourcing $VIM/sysinit.vim
003.619  000.060  000.060: require('core.global')
003.746  000.018  000.018: require('core.settings')
003.750  000.128  000.109: require('core.pack')
004.065  000.270  000.270: require('core.options')
004.182  000.062  000.062: require('keymap.bind')
004.290  000.222  000.160: require('core.mapping')
004.466  000.033  000.033: require('keymap.config')
004.892  000.601  000.568: require('keymap')
005.186  000.293  000.293: require('core.event')
006.595  000.518  000.518: require('catppuccin')
006.974  000.080  000.080: require('catppuccin.lib.hashing')
008.309  000.093  000.093: require('mason-core.functional')
008.371  000.057  000.057: require('mason-core.path')
008.448  000.076  000.076: require('mason.settings')
008.716  000.042  000.042: require('mason-core.functional.data')
008.719  000.119  000.077: require('mason-core.functional.function')
008.772  000.042  000.042: require('mason-core.functional.relation')
008.838  000.062  000.062: require('mason-core.functional.logic')
008.850  000.401  000.178: require('mason-core.platform')
008.865  000.793  000.166: require('mason-core.log')
009.129  000.152  000.152: require('mason-core.async')
009.171  000.041  000.041: require('mason-core.async.uv')
009.175  000.309  000.117: require('mason-core.fs')
009.252  000.075  000.075: require('mason-core.optional')
009.319  000.066  000.066: require('mason-core.EventEmitter')
009.471  000.151  000.151: require('mason-registry.index')
009.592  000.119  000.119: require('mason-core.functional.list')
009.597  001.617  000.104: require('mason-registry')
009.600  001.779  000.162: require('mason-tool-installer')
010.164  000.069  000.069: require('notify.util.queue')
010.166  000.201  000.133: require('notify.util')
010.315  000.147  000.147: require('notify.config.highlights')
010.318  000.480  000.131: require('notify.config')
010.369  000.049  000.049: require('notify.stages')
010.470  000.101  000.101: require('notify.service.notification')
010.870  000.084  000.084: require('notify.animate.spring')
010.872  000.143  000.059: require('notify.animate')
010.876  000.404  000.261: require('notify.windows')
011.296  000.167  000.167: require('notify.service.buffer.highlights')
011.299  000.308  000.142: require('notify.service.buffer')
011.301  000.424  000.115: require('notify.service')
011.480  000.177  000.177: require('notify.stages.util')
011.484  001.860  000.225: require('notify')
011.597  000.111  000.111: require('modules.ui.icons')
011.735  000.104  000.104: require('notify.stages.slide')
012.063  000.296  000.296: require('nvim_comment')
012.735  000.089  000.089: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/vim-go/ftdetect/gofiletype.vim
012.795  000.017  000.017: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/csv.vim/ftdetect/csv.vim
012.801  007.600  002.747: require('_compiled')
013.624  000.766  000.766: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/catppuccin/colors/catppuccin.vim
013.699  010.578  000.638: require('core')
013.722  010.621  000.044: sourcing /home/zzz/.config/nvim/init.lua
013.731  000.601: sourcing vimrc file(s)
014.062  000.017  000.017: sourcing /usr/share/vim/vimfiles/ftdetect/stp.vim
014.167  000.318  000.300: sourcing /usr/share/nvim/runtime/filetype.lua
014.192  000.013  000.013: sourcing /usr/share/nvim/runtime/filetype.vim
014.399  000.105  000.105: sourcing /usr/share/nvim/runtime/syntax/synload.vim
014.494  000.278  000.172: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
014.979  000.013  000.013: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
014.995  000.007  000.007: sourcing /usr/share/nvim/runtime/plugin/health.vim
015.012  000.009  000.009: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
015.027  000.008  000.008: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
015.050  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
015.187  000.007  000.007: sourcing /home/zzz/.local/share/nvim/rplugin.vim
015.193  000.135  000.128: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
015.274  000.073  000.073: sourcing /usr/share/nvim/runtime/plugin/shada.vim
015.293  000.007  000.007: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
015.318  000.013  000.013: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
015.336  000.008  000.008: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
015.362  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
015.387  000.014  000.014: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
015.606  000.064  000.064: sourcing /usr/share/nvim/runtime/plugin/man.lua
015.628  000.907: loading rtp plugins
015.934  000.028  000.028: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/mason-tool-installer.nvim/plugin/mason-tool-installer.lua
016.121  000.041  000.041: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
016.221  000.034  000.034: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
016.307  000.575: loading packages
016.784  000.477: loading after plugins
016.796  000.013: inits 3
017.131  000.334: reading ShaDa
017.539  000.226  000.226: require('packer.load')
018.656  000.006  000.006: require('vim.F')
018.666  000.977  000.971: require('alpha')
018.773  000.105  000.105: require('alpha.themes.dashboard')
019.701  000.068  000.068: require('accelerated-jk.config')
019.706  000.684  000.616: require('accelerated-jk')
019.822  000.089  000.089: require('accelerated-jk.time_driven')
019.871  000.886  000.113: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/accelerated-jk.nvim/plugin/accelerated-jk.vim
019.981  000.656: opening buffers
020.011  000.029: BufEnter autocommands
020.013  000.002: editing files in windows
020.199  000.063  000.063: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/copilot.lua/plugin/copilot.lua
021.249  000.112  000.112: require('copilot_cmp.format')
021.254  000.267  000.155: require('copilot_cmp.source')
021.255  000.888  000.622: require('copilot_cmp')
021.314  000.006  000.006: require('vim.keymap')
023.357  002.387: VimEnter autocommands
024.430  000.060  000.060: require('toggleterm.lazy')
024.484  000.050  000.050: require('toggleterm.constants')
024.834  000.348  000.348: require('toggleterm.terminal')
024.840  001.313  000.856: require('toggleterm')
025.067  000.106  000.106: require('toggleterm.colors')
025.173  000.104  000.104: require('toggleterm.utils')
025.177  000.332  000.122: require('toggleterm.config')
025.375  000.143  000.143: require('toggleterm.commandline')
025.424  000.279: UIEnter autocommands
025.870  000.347  000.347: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim
025.876  000.104: before starting main loop
026.062  000.022  000.022: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/specs.nvim/plugin/specs.vim
026.912  000.737  000.737: require('specs')
027.214  000.152  000.152: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/vim-cool/plugin/cool.vim
028.761  001.975: first screen update
028.781  000.020: --- NVIM STARTED ---

### Expected behavior

即时打开，对文件操作不卡顿

### Actual behavior

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Jint-lzxy**
Resolves #338.

@EternalChildren @ayamir @CharlesChiuGit Can you test this for me?
- **ssh:** `git clone git@github.com:Jint-lzxy/nvimdots.git && cd nvimdots && git checkout large-file-support`
- **https:** `git clone https://github.com/Jint-lzxy/nvimdots.git && cd nvimdots && git checkout large-file-support`
- **github CLI:** `gh pr checkout 394`

Sample file:
```sh
wget https://github.com/json-iterator/test-data/raw/master/large-file.json # file 1
wget https://zenodo.org/record/3227177/files/Android.tar.gz && tar -xf Android.tar.gz && rm -f Android.tar.gz # file 2
```
- file 1: `large-file.json` \~ 25 MiB
- file 2: `Android.log` \~ 183 MiB

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
I think it's a good patch for medium size files. It does improve a lot on `large-file.json`'s startup time.(from 11s to 1s)
But for extreme large files, like `Android.log`, this patch seems to have only minor improvement.

Some metrics on my machine, Arch(WSL):

Before this patch, compared with your main branch:
before

After:
after

Original(nvim --clean):
original

In original test, both files took under 1sec to load, so the clock didn't show up.

**Comment by Jint-lzxy** [comment]
That's true. There must be some other plugins that would need to read all the file contents before loading _(this will block the main process)_, but I'm not sure which they are.

**Comment by ayamir** [comment]
I noticed that `LunarVim/bigfile.nvim` provide min big file size, but only this feature can't satisfy the situation when the file is larger than 100MB like the file 2. So we'd better add a clean nvim for files which sizes are too large like which you do at https://github.com/ayamir/nvimdots/issues/338#issuecomment-1328978121.
`lua/core/init.lua`
```lua
local load_config = function()
	local pack = require("core.pack")
	createdir()
	disable_distribution_plugins()
	leader_map()

	pack.ensure_plugins()
	neovide_config()
	clipboard_config()

	require("core.options")
	require("core.mapping")
	require("keymap")
	require("core.event")
	pack.load_compile()

	-- vim.api.nvim_command([[set background=light]])
	vim.api.nvim_command([[colorscheme catppuccin]])
end

local load_core = function()
	local settings = require("core.settings")
	local load_big_files_faster = settings.load_big_files_faster
	if load_big_files_faster then
		local bigger_file_size = settings.bigger_file_size
		local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(vim.api.nvim_get_current_buf()))
		if ok and (stats == nil or stats.size < bigger_file_size) then
			load_config()
		end
	else
		load_config()
	end
end

load_core()
```
`lua/core/settings.lua`
```lua
-- default bigger_file_size = 100MB
settings["bigger_file_size"] = 100 * 1024 * 1024
```

**Comment by Jint-lzxy** [comment]
> I noticed that `LunarVim/bigfile.nvim` provides min big file size, but only this feature can't satisfy the situation when the file is larger than 100MB like the file 2.

That's true. However, if the user does not open the file directly, this issue still exists. The reason should be some plugins need to read all the contents of a file to work properly _(such as `treesitter` and `vim-illuminate`)_, so the best solution is to find the target plugins and disable them under the current buffer. Otherwise, users can only edit/view one large file in one neovim instance. All other functions are disabled.

**Comment by ayamir** [comment]
> However, if the user does not open the file directly, this issue still exists. 

This problem is not so salient than starting a new `nvim` instance for opening a large file by using this pr's solution.

**Comment by Jint-lzxy** [comment]
Indeed, I will modularize this feature when I have time.

**Comment by Jint-lzxy** [comment]
The indexing of `cmp-buffer` is the reason why it takes a long time to finish loading big files larger than 20MiB. This is consistent with the results in https://github.com/ayamir/nvimdots/pull/394#issuecomment-1368716190 _(`cmp-buffer` takes \~37s to finish indexing)_. Will consider disabling `nvim-cmp` to see if there is any improvement.

[(hrsh7th/cmp-buffer#performance-on-large-text-files)](https://github.com/hrsh7th/cmp-buffer#performance-on-large-text-files)

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit @ayamir Can you help me test this PR again? Many thanks ❤️

IMO the startup time is quite reasonable now _(this is very **close** to the startup time of `nvim --clean`)_<sup>[1,2]</sup>:
stat

One question: When should we load `bigfile.nvim`? It will block the main thread for some time, resulting in a slower startup time _(\~28ms delayed on my device)_<sup>[2]</sup>

*****
<sup>[1] This speed _(nvim --clean)_ can be called the "theoretical value" as there are still several necessary plugins that would be loaded before reading this file. The actual startup time could be slower than this.</sup>
<sup>[2] This test was performed on macOS. Due to the working mechanism of the darwin kernel, AFAIK the startup time will be a bit slower _(\~30ms)_ compared with other operating systems.</sup>

**Comment by ayamir** [comment]
image
`nvim` freezed after I press `<C-n>` try opening `nvim-tree`. Besides, there were always notifications   reported and never stopped.

**Comment by ayamir** [comment]
> image
> 
> `nvim` freezed after I press `<C-n>` try opening `nvim-tree`, I use `copilot` btw.
> 
> The reason maybe the notifications about lsp reported and never stopped, so them blocked the main thread.

Fixed after load `copilot` when `InsertEnter`.

**Comment by ayamir** [comment]
> One question: When should we load bigfile.nvim?

Maybe it's the best way now.

**Comment by Jint-lzxy** [comment]
> Fixed after load `copilot` when `InsertEnter` at [c3c0365](https://github.com/ayamir/nvimdots/commit/c3c0365d3dd0610d185aa610a8e6c46840e4ac03).

Ah I forgot to consider `copilot` 🤦‍♂️I will disable it like `lualine`: [`c43a2dc`#diff-R542-R548](https://github.com/ayamir/nvimdots/commit/c43a2dc5ccb875576c1db7f84856a902d87698a6#diff-f08b8700368e81128a8c78e6a78e1b8196d3a053e91854adf7f01f0338ed15c4R542-R548)

[(zbirenbaum/copilot.lua#filetypes)](https://github.com/zbirenbaum/copilot.lua#filetypes)

**Comment by Jint-lzxy** [comment]
@ayamir Will `copilot` attach to any large file buffers now?

**Comment by ayamir** [comment]
It will also freeze after `InsertEnter`. But if I open `LspInfo` after the notifications appears, it won't freeze.

**Comment by Jint-lzxy** [comment]
@ayamir Which servers are listed in `:LspInfo`? `copilot` shouldn't attach to these buffers at https://github.com/ayamir/nvimdots/pull/394/commits/01e68fe29028e3988defd7b0fd75f01834f13314.

**Comment by ayamir** [comment]
ok, no problems now.

**Review by ayamir — APPROVED** [review]

**Pull request merged**
