### PR TITLE
feat(ibl): support `indent-blankline` v3

### PR DESCRIPTION
**Pull request by CharlesChiuGit**
https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3
WIP

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
there isn't a 1-to-1 mapping of the old config to the new one, so i tried my best to adapt the v3 config.

the colorschme and the detail settings might need further adjustments.

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/1011/commits/115db0595a68b46ea72df5d7c69122640b317de1 updated several hl groups and added support for big files. It also mapped (almost) all v2 options to the corresponding valid entries in v3. The only exception here is `ibl.config.scope.include`: We presumably need more context/information (or upstream support) to make `indent-blankline.scope` work on all languages supported by Treesitter (https://github.com/lukas-reineke/indent-blankline.nvim/issues/632)

**Review by CharlesChiuGit — COMMENTED** [review]
LGTM

**Review by ayamir — APPROVED** [review]
LGTM

**Pull request merged**
