### PR TITLE
workaround(lsp-signature)!: fix input delay of nvim-cmp

### PR DESCRIPTION
**Pull request by Jint-lzxy**
* `on_attach` [is deprecated](https://github.com/ray-x/lsp_signature.nvim/blob/17ff7a405fea8376b015b8ea7910d2e59958bf68/doc/lsp_signature.txt#L148-L149);
* Now `lsp_signature` won't adjust its position relative to the completion popup to avoid problematic functions (cmp.visible) being called.

### CODE REVIEW

**Review by ayamir — APPROVED** [review]

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Comment by YuCao16** [comment]
Does this fix work for you? Because I'm still experiencing input delay on my end. If I disable `lsp_signature`, input delay disappears.

**Comment by Jint-lzxy** [comment]
@YuCao16 This PR only reduces calls to `cmp.visible()`, but as a matter of fact, u can completely eliminate related calls (since we disabled `check_completion_visible`) via this patch:
```diff
diff --git a/lua/lsp_signature/helper.lua b/lua/lsp_signature/helper.lua
index 8d09a22..c3e32d6 100644
--- a/lua/lsp_signature/helper.lua
+++ b/lua/lsp_signature/helper.lua
@@ -697,7 +697,7 @@ end
 helper.completion_visible = function()
   local hascmp, cmp = pcall(require, 'cmp')
   if hascmp then
-    return cmp.visible()
+    return true
   end

   return fn.pumvisible() ~= 0
```
The issue upstream is not _every_ call to `cmp.visible()` gets checked.

**Comment by Jint-lzxy** [comment]
Will #890 fix that?

**Comment by YuCao16** [comment]
> Will #890 fix that?

Yes, it works, thanks!

**Pull request merged**
