### PR TITLE
chore: cleanup and minor syntax improvements

### PR DESCRIPTION
**Pull request by Jint-lzxy**
This commit mainly tackled several minor touch-ups and syntax improvements:

- Addressed `luacheck` issues from previous commits.
- Added some to-do comments for `_buf_vtext`.
- Eliminated redundant/outdated options.
- Temporarily removed the ability to install nightly-version configs and updated the names of relevant functions: - `clone_by_https_or_ssh` -> `clone_repo`
- Rewrote `dotstutor` to make it more readable.

### CODE REVIEW

**Review by ayamir — APPROVED** [review]
LGTM

**Comment by ayamir** [comment]
In fact, I'm trying to use `vim.region()` in https://github.com/neovim/neovim/pull/13896#issuecomment-1621702052 to get selected text but failed. And I also see a relevant PR about it: https://github.com/neovim/neovim/pull/27578 and seem this api will be changed.
IMO current impl is enough for now.

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/1217/commits/65d580ee62a573ad7ff25bfd1d1c3ab905366e7b further simplified the `venv` detection logic in `dap/clients/python.lua`.

**Comment by Jint-lzxy** [comment]
> In fact, I'm trying to use `vim.region()` in ... to get selected text but failed. And I also see a relevant PR about it: ... and seem this api will be changed. IMO current impl is enough for 0.9.

Agreed. The new `vim.getregion()` is indeed more "reliable" due to its use of internal calls. Will update the to-do comment accordingly.

**Pull request merged**
