### PR TITLE
fix: make rust-analyzer could auto start

### PR DESCRIPTION
**Pull request by ClSlaid**
patch refers to:
https://github.com/simrat39/rust-tools.nvim/issues/397#issuecomment-1609662279

### CODE REVIEW

**Comment by ayamir** [comment]
Does this issue really exist? My `rust-analyzer` can start automatically when I `nvim main.rs`.

**Comment by ClSlaid** [comment]
> Does this issue really exist? My `rust-analyzer` can start automatically when I `nvim main.rs`.

`rust-analyzer` that unmanaged by `mason-lspconfig` will not automatically start and attach.

**Comment by Jint-lzxy** [comment]
I'm a bit dubious about whether this PR really fixes the problem. AFAIU it's possible that the `FileType` event is triggered _after_ the server(s) get attached, so the (newly) registered server isn't spawned by lspconfig automatically. Maybe a better solution is to explicitly tell lspconfig to load the new schema after `rust-tools` completes its startup (just blindly guessing, haven't verified this yet).

**Comment by ayamir** [comment]
> I'm a bit dubious about whether this PR really fixes the problem.

No, it doesn't work for me though the `rust-analyzer` installed from `rustup` and it can be found in my `PATH`. Close it.

**Pull request closed without merging**
