### PR TITLE
chore(lsp): update `html-lsp` registry

### PR DESCRIPTION
**Pull request by Groveer**
lsp cmd changed, look here: https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/html.lua

### CODE REVIEW

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Comment by CharlesChiuGit** [comment]
Personally I would prefer a more meaningful commit msg tho, but still thanks for your contribution!

**Comment by CharlesChiuGit** [comment]
Side note: It seems like the `mason` side and `nvim-lspconfig` side are not aligned.
https://github.com/williamboman/mason-lspconfig.nvim/blob/90a8bbf106b85b76951a34c542058ffa807de2b1/lua/mason-lspconfig/mappings/server.lua#L67

https://github.com/mason-org/mason-registry/blob/main/packages/html-lsp/package.yaml
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/html.lua

I'm not sure how does this two bridges together.

**Comment by ayamir** [comment]
AFAIK, none of them supports embeded javascript completion except https://github.com/vscode-langservers/vscode-html-languageserver-bin

**Comment by CharlesChiuGit** [comment]
Wow, sorry that I miss that lol

**Comment by Groveer** [comment]
So it was, pleace close the pr :sweat_smile:

**Pull request closed without merging**
