### PR TITLE
fix(null-ls): specify `rustfmt` manually

### PR DESCRIPTION
**Pull request by Jint-lzxy**
Haven't introduced `rustup` into the install script(s) yet cause I can't figure out how to automate this process 😢

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
https://github.com/CharlesChiuGit/dotfiles/blob/main/install_scripts/langs/rust.sh

maybe this would help

**Comment by Jint-lzxy** [comment]
The problem is we probably need to avoid installing multiple versions of Rust in parallel - so things become much more complex here, as Rust is distributed in multiple ways:
- **Self-hosted distribution** (some package managers e.g., [brew](https://formulae.brew.sh/formula/rust#default)): the package manager manages version control, `rustfmt` must be installed via `cargo`, but this has been deprecated; Besides, Rust is usually NOT installed on a standard path (aka `~/.cargo`).
- **The "legacy" official installer**: Similar to the official installer, except that `rustup` won't be installed (by default); `rustfmt` must be installed via `cargo`, or via `rustup` but `rustup` itself must be installed first.
- **The official installer, or the `rustup[-init]` package provided by many package mgrs**: The recommended approach.

So if we decide to automate this process, the following should be considered:
- **How to cleanup legacy installation(s)?** This seems to be far beyond the scope that the install script can handle;
- **How to execute rustup-init? (e.g., on MS Windows)** Spawning a child process **(the GUI version!)** will bring many uncertainties to the install script, as its operation is independent of the terminal. Hence to cover these cases the install script can be much more cumbersome - an unworthy trade-off, IMO.

**Comment by Jint-lzxy** [comment]
Thanks for the script! But the problem is we probably need to avoid installing multiple versions of Rust in parallel - so things become much more complex here, as Rust is distributed in multiple ways:
- **Self-hosted distribution** (some package managers e.g., [brew](https://formulae.brew.sh/formula/rust#default)): the package manager manages version control, `rustfmt` must be installed via `cargo`, but this has been deprecated; Besides, Rust is usually NOT installed on a standard path (aka `~/.cargo`).
- **The "legacy" official installer**: Similar to the official installer, except that `rustup` won't be installed (by default); `rustfmt` must be installed via `cargo`, or via `rustup` but `rustup` itself must be installed first.
- **The official installer, or the `rustup[-init]` package provided by many package mgrs**: The recommended approach.

So if we decide to automate this process, the following should be considered:
- **How to cleanup legacy installation(s)?** This seems to be far beyond the scope that the install script can handle;
- **How to execute rustup-init? (e.g., on MS Windows)** Spawning a child process **(the GUI version!)** will bring many uncertainties to the install script, as its operation is independent of the terminal. Hence to cover these cases the install script can be much more cumbersome - an unworthy trade-off, IMO.

**Comment by CharlesChiuGit** [comment]
aha, I didn't thought about those details, indeed this is important.
But due to it's complexity, I think it's better not to include it in the installation script.
Just put it in prerequisite should be fine IMO.

**Comment by Jint-lzxy** [comment]
IMO then we can just put a hint here, just like the `sqlite` one:
https://github.com/ayamir/nvimdots/blob/656e48a19732e06043e61ad54c28950980133313/scripts/install.ps1#L399-L402

**Comment by CharlesChiuGit** [comment]
that would do too. upvote for this

**Comment by Jint-lzxy** [comment]
Done :D https://github.com/ayamir/nvimdots/pull/852/commits/98e06787ba0c3b5506bfeb2653e973c13459f135
| Windows | \*nix |
|---------|-------|
| pwsh | zsh |

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Pull request merged**
