### PR TITLE
fix: merge user customized config with predefined.

### PR DESCRIPTION
**Pull request by ayamir**
https://github.com/ayamir/nvimdots/discussions/1375

### CODE REVIEW

**Comment by ayamir** [comment]
@JoeMob

**Comment by ayamir** [comment]
This commit has some problems, I will fix it later today.

**Comment by ayamir** [comment]
> This commit has some problems, I will fix it later today.

Done. @JoeMob @CharlesChiuGit

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Pull request merged**
