### PR TITLE
fix: utilize `ts-context` in `glance` preview window

### PR DESCRIPTION
**Pull request by mjkx5**
default zindex of glance [dnlhc/glance.nvim] floatterm is 45. It can display on glance.

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
how to trigger the error?

**Comment by mjkx5** [comment]
zindex 
nvim-treesitter/nvim-treesitter-context : default 20
dnlhc/glance.nvim: default 45, 
vim.api.nvim_open_win({zindex: })

---               • zindex: Stacking order. floats with higher `zindex` go on
---                 top on floats with lower indices. Must be larger than
---                 zero.

**Comment by CharlesChiuGit** [comment]
I'm not asking why, I'm asking how.

I don't see the point of setting `ts-context`'s `zindex` to a higher value.
`Glance` should be on top of other things since it's a temporary thing other than `ts-context`.

**Comment by mjkx5** [comment]
eeeeeeeeeeeeeeee

It is result of that config.

Screenshot_24-May_16-57-17_18805

if not that config, function SetNodeConfig() isn't display.

**Comment by mjkx5** [comment]
for example, I press `gh`, open the preview popup window. If not that config, I need `<c-w>h` into preview, then `[[` jump to position of function name. when look at function name, I realize if that is position that I want to jump to. 
if not, I neet to jump items list , to repeat next. If true, I need to return that position.

use that config, I don't need to jump function name.


In fact, that is still not the best, I need to jump left preview window to display function name. If cursor is right window, It display the function name, which is the best, but I don't have time to do that these two days.

**Comment by mjkx5** [comment]
for example, I look at `mod test` In preview window, I can realize that It isn't that I want. 
Screenshot_25-May_09-14-15_14005

**Comment by mjkx5** [comment]
In my case, `trim_scope` set inner better than outer. Have someone using inner?

**Comment by CharlesChiuGit** [comment]
> for example, I look at mod test In preview window, I can realize that It isn't that I want.

aha, that make sense to me now. tks for the clarification!

**Review by CharlesChiuGit — APPROVED** [review]
lgtm

**Comment by CharlesChiuGit** [comment]
> In my case, `trim_scope` set inner better than outer. Have someone using inner?

never tried it, i didn't notice major difference in my use case. but i think it's fine to change it.

**Comment by mjkx5** [comment]
@CharlesChiuGit  sorry, I am not familiar with pull request. I use --force, I accidentally delete your commit. please repeat commit.

**Comment by mjkx5** [comment]
@CharlesChiuGit I am not familiar with pull request. I accidentally used push --force, that delete your commit. 

Please repeat commit, thanks.

**Comment by mjkx5** [comment]
max_lines is set to 3. that means that It can display three lines in window header.

eg: if display text is 4 lines.

mod modName{
   func functionName{
      switch {
          A : 
          B:
      }
   }
}

In that case, set `inner` discard case A. set inner discard modname.

as comment, Which context lines to discard if `max_lines` is exceeded.

**Review by ayamir — APPROVED** [review]

**Review by ayamir — APPROVED** [review]

**Pull request merged**
