### PR TITLE
feat(ui): unified

### PR DESCRIPTION
**Pull request by huge-pancake**
1. Similar appearances for `cmp` and `wilder`.
2. Tidy appearance for `bufferline` working with `nvim-tree` and `outline (lspsaga)`.
3. Colored `indent-blankline`.
4. Similar appearances for indent lines in `nvim-tree`, `indent-blankline` and `outline (lspsaga)`.
5. New styles for float windows including `Telescope`.
6. Enabled highlights for `ts-context`, and its mode changed to `topline`.
7. Highlight names for `alpha` changed to the default.

Showcase

**Telescope**

image

**Bufferline** and **treesitter-context**

image

**cmp** and **wilder**

image

image

### CODE REVIEW

**Comment by ayamir** [comment]
Acceptable, need to be merged before 3.0.0 released.

**Comment by huge-pancake** [comment]
Cmp document highlights and cmp menu format updated.

**Comment by Saafo** [comment]
> Acceptable, need to be merged before 3.0.0 released.

Seems 3.0 didn't include this pr😢

**Comment by ayamir** [comment]
forgot to call for @Jint-lzxy ...

**Comment by huge-pancake** [comment]
There's a new style for `lualine` but I'm not sure it's mostly acceptable.

image

Tell me if you think it's acceptable.

**Comment by CharlesChiuGit** [comment]
> There's a new style for `lualine` but I'm not sure it's mostly acceptable.
> 
> image
> 
> Tell me if you think it's acceptable.
> 
> (lspsaga outline removed)

I'm thinking we can add git-blames in the middle of it?

**Comment by huge-pancake** [comment]
> > There's a new style for `lualine` but I'm not sure it's mostly acceptable.
> > image
> > Tell me if you think it's acceptable.
> > (lspsaga outline removed)
> 
> I like this one, but I'm thinking we can add git-blames in the middle of it?

Not sure about this, `gitsigns` already provides git blame at the end of current line.

**Comment by CharlesChiuGit** [comment]
i knw, i just don't like that lol
it's pretty annoying to me.
but it's not my repo, so it's not my call.

**Comment by Jint-lzxy** [comment]
> There's a new style for `lualine` but I'm not sure it's mostly acceptable.
> 
> image
> 
> Tell me if you like this.
> 
> (lspsaga outline removed)

Sorry for the delay, I'm also working on this 🤦‍♂️



Several thoughts:
- Perhaps `lualine_y` and `lualine_z` should be kept the same as before? Since they provide important information about document metadata & current cursor location;
- Loving the reimplementation of `lualine_a/b/c`, but would it be a bit repetitive to display filename at three different positions (bufferline, lspsaga, lualine)? Maybe we could replace that with `show_cwd`, but if so, we should support Windows:
https://github.com/ayamir/nvimdots/blob/56538b791d3354dd6a5af257be0bb3eaf52765bd/lua/modules/configs/ui/lualine.lua#L52-L54
- In terms of file status, I prefer to use glyphs to represent that _(instead of occupying `lualine_b`)_:
```lua
local function is_new_file()
	local filename = vim.fn.expand("%")
	return filename ~= "" and vim.bo.buftype == "" and vim.fn.filereadable(filename) == 0
end
local edit_status = {
	function()
		if vim.bo.modified then
			return icons.lualine.Modified
		elseif not vim.bo.modifiable or vim.bo.readonly then
			return icons.lualine.ReadOnly
		elseif is_new_file() then
			return icons.lualine.NewFile
		else
			return icons.lualine.Normal
		end
	end,
	color = function()
		return {
			fg = vim.bo.modified and colors.green
				or ((not vim.bo.modifiable or vim.bo.readonly) and colors.red or colors.lavender),
			bg = colors.surface0,
		}
	end,
	padding = { left = 1.2, right = 1.3 },
}
```

**Comment by Jint-lzxy** [comment]
> I like this one, but I'm thinking we can add git-blames in the middle of it?

@CharlesChiuGit Great idea, but now `lualine-c` is occupied by `git_status`. Would adding `git_blame` result in `lualine-c` being overcrowded?

**Comment by ayamir** [comment]
So should we keep `lspsaga winbar symbols` showed in `lualine`? Becase more visual elements are added, and the region of `lualine_c` will be fully occupied when in a deep embeded position. So the whole `lualine` looks bloated and can't show the complete `lspsaga winbar symbols`. Maybe let it just in the `winbar` will better.

**Comment by Jint-lzxy** [comment]
@ayamir I've removed that: https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537361782. But as a smaller matter, shall we enable `symbol_in_winbar.show_file`? Otherwise Winbar will be empty when there're no symbols to show (e.g., at `init.lua`).

Side effect: It will repeat with bufferline.

**Comment by ayamir** [comment]
> @ayamir I've removed that: [#718 (comment)](https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537361782). But as a smaller matter, shall we enable `symbol_in_winbar.show_file`? Otherwise Winbar will be empty when there're no symbols to show (e.g., at `init.lua`).
> 
> Side effect: It will repeat with bufferline.

I prefer to `show_file = false`.

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit Great idea, but now `lualine-c` is occupied by `git_status`. Would adding `git_blame` result in `lualine-c` being overcrowded?

Ys, if the commit is super long then is well be overcrowded.

> So should we keep `lspsaga winbar symbols` showed in `lualine`? Becase more visual elements are added, and the region of `lualine_c` will be fully occupied when in a deep embeded position. So the whole `lualine` looks bloated and can't show the complete `lspsaga winbar symbols`. Maybe let it just in the `winbar` will better.

Root for taking `winbar` back.

> I've removed that: https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537361782. But as a smaller matter, shall we enable `symbol_in_winbar.show_file`? Otherwise Winbar will be empty when there're no symbols to show (e.g., at `init.lua`).
>
> Side effect: It will repeat with bufferline.

Personally I think it's fine to disable `symbol_in_winbar.show_file`. 
In terms of user experience, we still need to wait for lsp to give us the diagnostics for few sections sometime. So I think it's okay to let the winbar to popup.

**Comment by huge-pancake** [comment]
* I'm only free at Chinese weekends, the following 5 days I can't do anything...

**Comment by CharlesChiuGit** [comment]
> * I'm only free at Chinese weekends, the following 5 days I can't do anything...

It's okay lol. We all are, well, in a certain level.

**Comment by CharlesChiuGit** [comment]
I like the gray-out effect on the git diffs and the smaller gaps between diagnostics.

Other parts I like @Jint-lzxy 's version more.


Not being offensive, just from a pure personal aesthetic perspective.

**Comment by Jint-lzxy** [comment]
> I like the gray-out effect on the git diffs and the smaller gaps between diagnostics.

Also loving the reimplementation of `lualine_a/b/c` 😄 I'll merge these two versions into one.

**Comment by ayamir** [comment]
I'd like @Jint-lzxy left part and @huge-pancake right part combined personally.

**Comment by huge-pancake** [comment]
I'm back! Should we merge it soon or we wait for the new lualine config completely done?

My current lualine config

```lua
return function()
	local icons = {
		diagnostics = require("modules.utils.icons").get("diagnostics", true),
		misc = require("modules.utils.icons").get("misc", true),
		git = require("modules.utils.icons").get("git", true),
		ui = require("modules.utils.icons").get("ui", true),
	}

	local function diff_source()
		local gitsigns = vim.b.gitsigns_status_dict
		if gitsigns then
			return {
				added = gitsigns.added,
				modified = gitsigns.changed,
				removed = gitsigns.removed,
			}
		end
	end

	local function lsp_status()
		if rawget(vim, "lsp") then
			for _, client in ipairs(vim.lsp.get_active_clients()) do
				if client.attached_buffers[vim.api.nvim_get_current_buf()] and client.name ~= "null-ls" then
					return (vim.o.columns > 100 and "%#St_LspStatus#" .. " LSP [" .. client.name .. "]") or " LSP"
				end
			end
		end
	end

	local function get_cwd()
		local cwd = vim.fn.getcwd()
		local is_windows = require("core.global").is_windows
		if not is_windows then
			local home = require("core.global").home
			if cwd:find(home, 1, true) == 1 then
				cwd = "~" .. cwd:sub(#home + 1)
			end
		end
		return icons.ui.RootFolderOpened .. cwd
	end

	local mini_sections = {
		lualine_a = { "filetype" },
		lualine_b = {},
		lualine_c = {},
		lualine_x = {},
		lualine_y = {},
		lualine_z = {},
	}
	local outline = {
		sections = mini_sections,
		filetypes = { "lspsagaoutline" },
	}
	local diffview = {
		sections = mini_sections,
		filetypes = { "DiffviewFiles" },
	}

	local function python_venv()
		local function env_cleanup(venv)
			if string.find(venv, "/") then
				local final_venv = venv
				for w in venv:gmatch("([^/]+)") do
					final_venv = w
				end
				venv = final_venv
			end
			return venv
		end

		if vim.bo.filetype == "python" then
			local venv = os.getenv("CONDA_DEFAULT_ENV")
			if venv then
				return string.format("%s", env_cleanup(venv))
			end
			venv = os.getenv("VIRTUAL_ENV")
			if venv then
				return string.format("%s", env_cleanup(venv))
			end
		end
		return ""
	end

	local colors = require("modules.utils").get_palette()
	local custom_catppuccin = require("lualine.themes.catppuccin")
	custom_catppuccin.normal.c.fg = colors.overlay0

	require("lualine").setup({
		options = {
			icons_enabled = true,
			theme = custom_catppuccin,
			disabled_filetypes = {},
			component_separators = "",
			section_separators = { left = "", right = "" },
		},
		sections = {
			lualine_a = {
				{
					"mode",
					fmt = function(name)
						return icons.misc.Vim .. name
					end,
				},
			},
			lualine_b = {
				{ "filetype", colored = false, icon_only = true, padding = { left = 1 } },
				{ "filename" },
			},
			lualine_c = {
				{ "branch", icon = string.sub(icons.git.Branch, 1, 4), padding = { left = 1 } },
				{
					"diff",
					colored = false,
					symbols = {
						added = icons.git.Add,
						modified = icons.git.Mod,
						removed = icons.git.Remove,
					},
					source = diff_source,
				},
				-- This can make things after this in section c centered
				-- function()
				-- 	return "%="
				-- end,
			},
			lualine_x = {
				{
					"diagnostics",
					sources = { "nvim_diagnostic" },
					sections = { "error", "warn", "info", "hint" },
					symbols = {
						error = icons.diagnostics.Error,
						warn = icons.diagnostics.Warning,
						info = icons.diagnostics.Information,
						hint = icons.diagnostics.Hint,
					},
				},
				lsp_status,
			},
			lualine_y = {
				get_cwd,
				python_venv,
			},
			lualine_z = { "location" },
		},
		inactive_sections = {
			lualine_a = {},
			lualine_b = {},
			lualine_c = { "filename" },
			lualine_x = { "location" },
			lualine_y = {},
			lualine_z = {},
		},
		tabline = {},
		extensions = {
			"quickfix",
			"nvim-tree",
			"nvim-dap-ui",
			"toggleterm",
			"fugitive",
			outline,
			diffview,
		},
	})
end
```

**Comment by huge-pancake** [comment]
Also IMO the similar things should be in one place, for example, filename, filetype (icon) and file format should be in same place but not place the filename on the left and others on the right.

**Comment by CharlesChiuGit** [comment]
> Should we merge it soon or we wait for the new lualine config completely done?

i prefer merge when things r settled

**Comment by CharlesChiuGit** [comment]
> Also IMO the similar things should be in one place, for example, filename, filetype (icon) and file format should be in same place but not place the filename on the left and others on the right. @Jint-lzxy 

seems like a gd idea

**Comment by Jint-lzxy** [comment]
> Also IMO the similar things should be in one place, for example, filename, filetype (icon) and file format should be in same place but not place the filename on the left and others on the right.

Agreed. (https://github.com/ayamir/nvimdots/pull/718#issuecomment-1537371594)

> Should we merge it soon or we wait for the new lualine config completely done?

We need to wait until the upstream PR https://github.com/catppuccin/nvim/pull/481 gets merged. It will introduce many changes.

**Comment by ayamir** [comment]
Can't wait to merge it

**Comment by Jint-lzxy** [comment]
IMHO we can first merge the commits that won't change their states due to upstream changes (such as `cmp`, `wilder`).

**Comment by huge-pancake** [comment]
> IMHO we can first merge the commits that won't change their states due to upstream changes (such as `cmp`, `wilder`).

Sure

**Comment by huge-pancake** [comment]
New style for `nvim-tree`

image

**Comment by huge-pancake** [comment]
The other customization will be divided in some other prs, unsure new styles will be discussed at #698.

**Pull request closed without merging**
