### PR TITLE
use Legendary to provide command panel like VSCode

### PR DESCRIPTION
**Pull request by ayamir**

### CODE REVIEW

**Comment by ayamir** [comment]
`<C-p>` to open the command panel.

**Comment by Jint-lzxy** [comment]
Great feature! Gonna test for a few days to see if there are any potential problems 👍

**Review by Jint-lzxy — COMMENTED** [review]
Great feature! Gonna test for a few days to see if there are any potential problems 👍

**Comment by ayamir** [comment]
I want to merge it quickly, It can works normally in my daily use.

**Review by Jint-lzxy — APPROVED** [review]

**Pull request merged**
