### PR TITLE
feat(ui)!: improve user experience wrt transparent bg

### PR DESCRIPTION
**Pull request by Jint-lzxy**
As per #864. Using the alternative method.

### CODE REVIEW

**Comment by ayamir** [comment]
image

Seems `nvim-treesitter-context` doesn't support this.

**Comment by Jint-lzxy** [comment]
Fixed at https://github.com/ayamir/nvimdots/pull/865/commits/695871655cb2b0f2ecb4f2074e12fb509387638f.

**Review by ayamir — APPROVED** [review]
LGTM now 👍

**Review by CharlesChiuGit — APPROVED** [review]
LGTM

**Pull request merged**
