### PR TITLE
Migrate to mason due to deprecation of nvim-lsp-installer

### PR DESCRIPTION
**Pull request by ayamir**

### CODE REVIEW

**Review by ayamir — COMMENTED** [review]
migration without error for fresh installation and old users.

**Comment by ayamir** [comment]
@jczhang02 can you review this pr?

**Review by jczhang02 — COMMENTED** [review]
I have tested the commit in this PR.

**Review by jczhang02 — APPROVED** [review]
The perfect modification.

**Review by jczhang02 — APPROVED** [review]
Approved

**Pull request merged**
