### PR TITLE
feat(ui)!: unify UI components: cmp, wilder, floats

### PR DESCRIPTION
**Pull request by Jint-lzxy**
https://github.com/ayamir/nvimdots/pull/718#issuecomment-1567045025. Further changes:
- Used branch: `refactor/syntax-highlighting` that has not yet been merged:
```lua
ui["Jint-lzxy/nvim"] = {
	lazy = false,
	branch = "refactor/syntax-highlighting",
	name = "catppuccin",
	config = require("ui.catppuccin"),
}
```
- Simplified `cmp.formatting.format()`
- **Pinned `cmp-treesitter` at commit `c8e3a74` b/c we probably don't need that new feature, and it's also a source of trouble.**

<sub>---------</sub>
<sub>Signed-off-by: Jint-lzxy \<50296129+Jint-lzxy@users.noreply.github.com\></sub>
<sub>Co-authored-by: huge-pancake \<huge.pancake.zxr@gmail.com\></sub>

### CODE REVIEW

**Comment by Jint-lzxy** [comment]
cc @huge-pancake

**Comment by ayamir** [comment]
LGTM for current UI, but seems lack the change of `lspsaga outline` and `lualine`.

**Review by ayamir — APPROVED** [review]

**Comment by huge-pancake** [comment]
Current at school so that can't review now. Will have a look on this weekend.

**Comment by Jint-lzxy** [comment]
> But after the entry name like `[LSP]` set, other completion candidates provided by vanilla `nvim` which have no such entry name look like something is missing. Maybe we should disable it at later commits.

The `__index` metamethod would do the trick :)

**Comment by CharlesChiuGit** [comment]
Is some candidates got cross out intended? 
圖片

**Review by CharlesChiuGit — APPROVED** [review]
LGTM! this is super nice!

**Comment by ayamir** [comment]
I disabled nvim built-in completion by set `complete = ""` and `completeopt = ""` in `options.lua` but didn't work. So the candidates without menu may be produced by other sources.

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/772/commits/c81165b6e1cc6bae94cfafba53d83b67b889b575

> Addition on ayamir mentioned, is some candidates got cross out intended?

Ys they are defined by the language server (usually denoting this entry is deprecated).

**Comment by Jint-lzxy** [comment]
> I disabled nvim built-in completion by set `complete = ""` and `completeopt = ""` in `options.lua` but didn't work. So the candidates without menu may be produced by other sources.

Can't wrap my head around this 😢 I've never encountered this issue before (copilot disabled)

Is it related to `completefunc`? `:h complete-functions`

**Comment by ayamir** [comment]
> > I disabled nvim built-in completion by set `complete = ""` and `completeopt = ""` in `options.lua` but didn't work. So the candidates without menu may be produced by other sources.
> 
> Can't wrap my head around this 😢 I've never encountered this issue before (copilot disabled)
> 
> Is it related to `completefunc`? `:h complete-functions`

OK now, the unknown source is treesitter.

**Pull request merged**
