### PR TITLE
feat: search with selection text.

### PR DESCRIPTION
**Pull request by ayamir**
image

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
i'll take a look when i get back to work. no pc by hand now lol.

**Comment by ayamir** [comment]
Wonder why the code lint was not passed. 🤨

**Comment by CharlesChiuGit** [comment]
> Wonder why the code lint was not passed. 🤨

```
Checking lua/keymap/tool.lua                      1 warning

    lua/keymap/tool.lua:136:56: accessing undefined variable _buf_vtext
```

**Comment by CharlesChiuGit** [comment]
functionality it works

**Comment by CharlesChiuGit** [comment]
[`b3ed6ca` (#1175)](https://github.com/ayamir/nvimdots/pull/1175/commits/b3ed6cafe82be67bdb56d334508e9d8ee34fe96d)

this might do the trick lol

**Review by CharlesChiuGit — APPROVED** [review]
LGTM! very useful feature lol

**Pull request merged**
