### PR TITLE
refactor(telescope-frecency)!: remove support for `sqlite.lua`

### PR DESCRIPTION
**Pull request by CharlesChiuGit**
https://github.com/nvim-telescope/telescope-frecency.nvim?tab=readme-ov-file#remove-dependency-for-sqlitelua
WIP

might to trigger `:FrecencyMigrateDB` and `:FrecencyValidate` to some ppl.

### CODE REVIEW

**Review by Jint-lzxy — APPROVED** [review]
Mostly LGTM, except for the NixOS part (I can’t test this right away).

p.s. We might also need to remove the "sqlite"-related section(s) from the wiki :D

**Comment by CharlesChiuGit** [comment]
@misumisumi would u might share some of your wisdom? lol

**Comment by misumisumi** [comment]
I checked and it works fine without `sqlite`.
Since the necessary work on NixOS has already been completed with @Jint-lzxy 's `9cb82d5`, we can merge them.

**Review by CharlesChiuGit — COMMENTED** [review]
LGTM

**Review by ayamir — APPROVED** [review]

**Pull request merged**
