### PR TITLE
fix: use `s1n7ax/nvim-window-picker` to provide picker for `nvim-tree`

### PR DESCRIPTION
**Pull request by ayamir**

### CODE REVIEW

**Comment by ayamir** [comment]
reference: https://github.com/nvim-tree/nvim-tree.lua/blob/9e4c39572f631bb60ee15cb9d46e1daa9927a45e/doc/nvim-tree-lua.txt#L1009

**Comment by ayamir** [comment]
Add a new plugin can solve #391, but I don't know whether there is a better solution.

**Comment by CharlesChiuGit** [comment]
I can't seem to reproduce #391, even after update all plugins and nvim itself(0.9.0 nightly).

**Comment by CharlesChiuGit** [comment]
I can only confirmed that after using this patch, nvim-tree still works as expected as usual.

**Review by CharlesChiuGit — APPROVED** [review]
LGTM.

**Review by Jint-lzxy — CHANGES_REQUESTED** [review]
I don't think this is the problem. I haven't encountered similar issues when using macOS+iTerm2 with [my configuration](https://github.com/Jint-lzxy/nvimconfig). Guess this is related to buffer events.

I'll do a git bisect now to check which commit introduced this problem 👍

**Comment by Jint-lzxy** [comment]
A reliable reproduction steps of the problem is here: https://github.com/ayamir/nvimdots/issues/391#issuecomment-1367827005. Guess this is an upstream issue.

**Review by Jint-lzxy — APPROVED** [review]
https://github.com/ayamir/nvimdots/issues/391#issuecomment-1368662179

**Comment by CharlesChiuGit** [comment]
nvim-tree has introduce a new event call `TreeAttachedPost`, maybe we can make use of it.

**Pull request merged**
