### PR TITLE
feat: add setting for copilot enable or not.

### PR DESCRIPTION
**Pull request by ayamir**
Not all users use copilot and not all situations we need it. So I add a switch to it. (Sorry for the wrong branch name)

### CODE REVIEW

**Comment by CharlesChiuGit** [comment]
hmmm, it would make a mess if we include `tabline` and `codeium`. maybe just leave it along.

**Comment by fecet** [comment]
maybe also good to add some other AI stuff like chatgpt.nvim

**Review by Jint-lzxy — APPROVED** [review]
IMO we can leave this PR unchanged cause copilot has a large user base, thus shipping copilot with our base config makes sense to me. For those other plugins (possible candidates for extras), @fecet proposed in https://github.com/ayamir/nvimdots/issues/888#issuecomment-1649739665 that we can "use our custom loader (to) import extras like LazyVim". FWIW this is just trivial amount of work and can be implemented together w/ #931 😄

**Comment by ayamir** [comment]
Making it `true` by default won't influence the current user experience.

**Comment by ayamir** [comment]
> maybe also good to add some other AI stuff like chatgpt.nvim

Haven't tried it because my free api key expired before lol

**Pull request merged**
