### PR TITLE
patch: update neodim

### PR DESCRIPTION
**Pull request by ClSlaid**
Current neodim.nvim version is not compatible with high versioned Neovim.

https://github.com/zbirenbaum/neodim/issues/43

### CODE REVIEW

**Review by ayamir — CHANGES_REQUESTED** [review]
It's better exclude `lazy-lock.json` to commit changes.

**Comment by ayamir** [comment]
Current neodim doesn't support nvim stable release, so it's not the time to update it.
image

**Comment by ClSlaid** [comment]
Ok, let's redirect this PR to 0.10 branch then.

**Comment by ayamir** [comment]
I merged main into 0.10 just now, close this PR and open a new one plz.

**Pull request closed without merging**
